// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe1GHrpimaCZ2fOT3gEatKcJAlZB8kYw4',
    appId: '1:450316132885:web:65f46aa0477903685ce41c',
    messagingSenderId: '450316132885',
    projectId: 'songvoter-852f0',
    authDomain: 'songvoter-852f0.firebaseapp.com',
    storageBucket: 'songvoter-852f0.appspot.com',
    measurementId: 'G-PSD9PH393R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE94J4zNnK2lIB1MWtLHjQuY22r59iBeQ',
    appId: '1:450316132885:android:2bda966f3567fd265ce41c',
    messagingSenderId: '450316132885',
    projectId: 'songvoter-852f0',
    storageBucket: 'songvoter-852f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6aGg-ZqYgQfhOvXOBQX9QkdeoVBC0ex4',
    appId: '1:450316132885:ios:301a448b7dfc506e5ce41c',
    messagingSenderId: '450316132885',
    projectId: 'songvoter-852f0',
    storageBucket: 'songvoter-852f0.appspot.com',
    androidClientId: '450316132885-2a1k6vmlno1tl530c7he4gicgil2j37g.apps.googleusercontent.com',
    iosClientId: '450316132885-vfp0slsloa356175kvivj3n6m00njopr.apps.googleusercontent.com',
    iosBundleId: 'com.example.songVoter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6aGg-ZqYgQfhOvXOBQX9QkdeoVBC0ex4',
    appId: '1:450316132885:ios:301a448b7dfc506e5ce41c',
    messagingSenderId: '450316132885',
    projectId: 'songvoter-852f0',
    storageBucket: 'songvoter-852f0.appspot.com',
    androidClientId: '450316132885-2a1k6vmlno1tl530c7he4gicgil2j37g.apps.googleusercontent.com',
    iosClientId: '450316132885-vfp0slsloa356175kvivj3n6m00njopr.apps.googleusercontent.com',
    iosBundleId: 'com.example.songVoter',
  );
}
